ALTER TYPE deployment_status ADD VALUE IF NOT EXISTS 'SUSPENDING';
ALTER TYPE deployment_status ADD VALUE IF NOT EXISTS 'SLEEPING';
ALTER TYPE deployment_status ADD VALUE IF NOT EXISTS 'WAKING';
ALTER TYPE deployment_status ADD VALUE IF NOT EXISTS 'STOPPING';
ALTER TABLE deployments
 ADD COLUMN last_request_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 ADD COLUMN idle_epoch INTEGER NOT NULL DEFAULT 0,
 ADD COLUMN idle_attempts INTEGER NOT NULL DEFAULT 0,
 ADD COLUMN idle_error TEXT,
 ADD COLUMN cold_start_ms BIGINT;
